project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:
  - source: ".github/translations/*.po"
    translation: "emhttp/languages/%locale%/*.po"
  - source: "emhttp/languages/en_US/*.txt"
    translation: "emhttp/languages/%locale%/*.txt" 