project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: '.github/translations/unraid-webgui-js.po'
    translation: 'translations/%locale%/webgui-js.po'
    type: 'po'
    
  - source: '.github/translations/unraid-webgui-final-fixed.po'
    translation: 'translations/%locale%/webgui-final-fixed.po'
    type: 'po' 